export const LAGOS_WARDS: Record<string, readonly string[]> = {
  "Agege": [
    "ATOBAJE",
    "AWORI ONIWAYA",
    "DOPEMU",
    "ISALE ODO/AYIGE",
    "ISALE OJA",
    "KEKE",
    "OKEKOTO",
    "ORILE",
    "OYEWOLE/ALAAGBA",
    "PAPA ASHAFA",
    "PAPA UKU/ OLUSANYA",
    "POWERLINE/OKO-OBA",
    "SANGO",
  ],
  "Ajeromi-Ifelodun": [
    "AIYETORO",
    "AJEGUNLE",
    "ALABA",
    "ALAKOTO/Ibafon",
    "AMUKOKO",
    "APASA Amukoko",
    "AWODI-ORA",
    "BALE ALAYABIAGBA",
    "IBAFON",
    "LAYENI-Okoya",
    "OJORA Amukoko",
    "OKE OJA",
    "OLUWA/AKERE",
    "OWOYEMI",
    "TEMIDIRE",
    "TOLU",
  ],
  "Alimosho": [
    "ABARANJE/OKERUBE",
    "ABESAN I",
    "ABESAN II",
    "ABORU",
    "ABULE EGBA",
    "AGBELEKALE",
    "AJASA/AMIKANLE",
    "AKESAN-Obadore",
    "AKOWONJO/ILUPEJU",
    "ALAGBADO/ALAKUKO",
    "ALAGUNTAN",
    "ATAN Lagos",
    "AYOBO",
    "Alabata",
    "BADA-MEGIDA",
    "BARUWA",
    "EGAN",
    "EGBE-AGODO",
    "EGBE-LIASU",
    "EGBEDA",
    "GOWON ESTATE",
    "IDIMU",
    "IGANDO",
    "IJEGUN",
    "IKOTUN",
    "IPAJA",
    "ISHERI OSHUN",
    "ISHERI-OLOFIN",
    "MOSAN/AKINOGGUN",
    "OGUNTADE/BAMEKE",
    "OKE-ODO",
    "OKI",
    "OKUNOLA",
    "OMITUNTUN-OLORI",
    "SANTOS/ILUPEJU",
    "UNITY ESTATE",
  ],
  "Amuwo-Odofin": [
    "ABULE OSUN ONIREKE",
    "ADO SOBA",
    "AGBOJU &ENVIRON",
    "EKO AKETE",
    "IBESHE& ENVIRON",
    "IFELODUN",
    "IJEGUN",
    "ILADO TOMARO",
    "IREDE",
    "IREPODUN",
    "KIRIKIRI & ENVIRON",
    "Kuje",
    "ODOFIN",
    "ORIRE",
  ],
  "Apapa": [
    "ABETE",
    "ABRAHAM ADESANYA",
    "ALAFIA",
    "ANJORIN",
    "APAPA",
    "BADIA",
    "GASKIYA",
    "IJORA",
    "MARINE BEACH",
    "ODUDUWA",
    "OWOSENI",
    "SARI",
  ],
  "Badagry": [
    "AHOVIKOH",
    "AJARA TOPA",
    "AJARA VETHO",
    "AJIDO",
    "AKORO",
    "APA",
    "ARADAGUN-MOWO",
    "ARAROMI-ALE",
    "AWHANJIGOH",
    "GBETHROME",
    "IBEREKO",
    "IKOGA",
    "ILOGBO",
    "ISALU/IYAFIN",
    "IWORO-GBANKO",
    "JEGBA QUARTERS",
    "KWEME",
    "POSUKOH",
    "TOPO-IDALE",
    "WESERE",
  ],
  "Epe": [
    "AGBOWA I",
    "AGBOWA II/ADO",
    "AIYETORO/LAGBADE/AGBALA/OLOTA",
    "AJAGANABE",
    "AJEBO ORUGBO",
    "BADO/EBOLE/ETITA/IBERIKODO",
    "EJIRIN/KETU",
    "IBONWON",
    "IFESOWAPO/TEMU OKE-OSO",
    "ILARA",
    "ISALE AGORO/OKE-BALOGUN/OGUNMUDE ERESE",
    "MAYUNRE-ORIBA/OREPETE-ITO OMU",
    "NAFORIJA/POKA",
    "ODOMOLA",
    "ODORAGUNSIN",
    "OLUGBOKERE/ABOMITI",
    "OWU/OTA",
    "PAPA",
    "SAGIDA/OKEPOSU",
  ],
  "Eti-Osa": [
    "1004/ABOYADE",
    "ADDO/OKEIRA",
    "AJAH",
    "AJIRAN/OSAPA",
    "APESE/VI EXTENSION",
    "BADORE/LANGBASA",
    "FALOMO/OYINKAN ABAYOMI",
    "IGBO-EFON/MAIYEGUN",
    "IJEH/DOLPHIN ESTATE",
    "IKATE/LEKKI",
    "IKOYI I",
    "IKOYI II",
    "ILASAN/ORILE",
    "KURAMO SCHOOL/Lekki",
    "MAROKO/OKUN ALFA",
    "OBALENDE",
    "OKUN AJAH/OKUNMOPO",
    "SANGOTEDO",
    "TARKWA BAY",
    "VI",
  ],
  "Ibeju-Lekki": [
    "IBEJU I",
    "IBEJU II",
    "ISE/IGBOGUN",
    "IWEREKUN I",
    "IWEREKUN II",
    "LEKKI I",
    "LEKKI II",
    "ORIMEDU I",
    "ORIMEDU II",
    "ORIMEDU III",
    "SIRIWON/ IGBEKODO I",
    "SIRIWON/ IGBEKODO II",
  ],
  "Ifako-Ijaiye": [
    "ABULE EGBA/ILUPEJU",
    "AGBADO DALEMO",
    "ALAGBADO/KOLLINTON",
    "ALAKUKO AJEGUNLE",
    "IFAKO PELE",
    "IFAKO/COKER",
    "IJAIYE GBIRINMI",
    "IJAIYE OJOKORO",
    "IJAIYE OKE-IRA",
    "IJAIYE/IFAKO",
    "IJU ISHAGA",
    "IJU OBAWOLE",
    "IJU OGUNDIMU",
    "Tabon Tabon/EGBIR",
  ],
  "Ikeja": [
    "AGUDA",
    "AKIODE",
    "ALADE",
    "ALAUSA",
    "ANIFOWOSHE",
    "G.R.A.",
    "OGBA/OLUWOLE",
    "OJODU",
    "OKE-IRA CENTRAL",
    "OKE-IRA POWERLINE",
    "OLUSOSUN",
    "ONIGBONGBO",
    "ONILEKERE",
    "OPEBI",
    "OREGUN",
    "ORILE IKEJA",
    "SERIKI-ARO",
    "WASIMI",
  ],
  "Ikorodu": [
    "ABOSAN",
    "AGA/IJOMU",
    "AGBALA/ LASUNWON",
    "AGURA/GBERIGBE",
    "AIGE/SOLOMADE",
    "AJAGURO",
    "ATERE",
    "AYEGBAMI/ODORO",
    "BAIYEKU/ORITA/OFFIN",
    "EGBIN/ITUNOLIWO",
    "ELEPE",
    "ERIKORODO",
    "IBESHE",
    "IGBOKUTA/OKE-AGBO/IGBALU",
    "IPAKODO",
    "ISAWO",
    "ISELE",
    "ISIU",
    "ITUMOKUN",
    "ITUNPATE/ITUMAJA",
    "MAJA",
    "MAJIDUN",
    "ODOGUNYAN",
    "OKE-ELETU/ABULE-EKO",
    "OKE-OYINBO/ AIYETORO",
    "OLORI/EYITA",
    "OLORUNDA",
    "OWUTU",
    "SHOLAFUN/AGBELE",
    "TONABU/OPOPO",
  ],
  "Kosofe": [
    "AGBOYI I",
    "AGBOYI II",
    "AGIDI/ORISHIGUN",
    "AGILITI/MAIDAN",
    "ANTHONY",
    "ARAROMI/IFAKO",
    "AROWOSEGBE/ALAPERE",
    "BAMGBE/ELEBIJU",
    "ERUKAN/ORISHIGUN",
    "IDERA",
    "IKOSI-OKE",
    "ISHERI/OLOWORA",
    "MENDE",
    "ODO-OGUN/AJEGUNLE",
    "OGUDU",
    "OJOTA",
    "OLUBORI/MOSAFEJO",
    "ORILE OWORO",
    "ORILE-IKOSI",
    "ORILE-KETU",
    "SHANGISHA/MAGODO",
  ],
  "Lagos Island": [
    "AJELE",
    "ALAGBA/OBADINA",
    "ANIKANTAMO",
    "ARAROMI ODO",
    "BALOGUN",
    "EPETEDO EAST",
    "EPETEDO WEST",
    "IDUMOYINGBO",
    "IDUNGANRAN/IDUMAGBO",
    "ILUPESI/EBUTE AWO",
    "ISALE GANGAN",
    "LAFIAJI",
    "ODAM",
    "OKE-ARIN/IDUMOTA",
    "OKE-OLOWOGBOWO",
    "OKEPOPO EAST",
    "OKEPOPO WEST",
    "OKO-AWO/AGARAWU",
    "OLOSUN/OJO OTO",
    "OLUWOLE",
  ],
  "Lagos Mainland": [
    "ABULE IJESHA",
    "ABULE OJA",
    "ADEKUNLE/AIYETORO",
    "ADERUPOKO/IJEBU QTERS",
    "ALAGOMEJI",
    "ALOBA/DESALU",
    "ARAROMI",
    "BOTANICAL GARDEN",
    "FREEMAN/GLOVER",
    "HARVEY",
    "IPONRI/OLALEYE",
    "MAKOKO",
    "OJO-ONIYUN",
    "OKOBABA",
    "ONIKE/OYADIRAN",
    "OTTO",
    "OYINGBO",
    "SALAMI/ BAIYEWUNMI",
  ],
  "Mushin": [
    "ALAFIA/ ADEOYO",
    "ALAKARA",
    "BABALOSA I",
    "BABALOSA II",
    "IDI-ARABA",
    "IDI-ORO/ODI OLOWO",
    "IGBEHIN",
    "ILUPEJU",
    "ILUPEJU INDUSTRIAL",
    "KAYODE/FADEYI",
    "MOSHALASHI/AGORO",
    "MUSHIN/ATEWOLARA",
    "ODO ERAN/OGUNLANA",
    "ODUSELU/OLA",
    "OJUWOYE",
    "OLATEJU",
    "ONITIRE",
    "OWODUNNI",
    "PAPA AJAO",
  ],
  "Ojo": [
    "AJANGBADI",
    "EGAN",
    "ETEGBIN",
    "IBA",
    "IGBO-ELERIN",
    "IJANIKIN",
    "ILOGBO- ELEGBA",
    "IRA",
    "IREWE",
    "KEMBERI",
    "OJO TOWN",
    "OKOKOMAIKO",
    "OTO-AWORI",
    "SABO-ONIBA",
    "TAFFI",
  ],
  "Oshodi-Isolo": [
    "AFARIOGUN",
    "AIGBAKA",
    "AILEGUN",
    "AJAO ESTATE",
    "AKINGBAYE",
    "ALAGBEJI",
    "APENA",
    "EWUTUNTUN",
    "FADU",
    "IFOSHIN",
    "IGBEHINADUN",
    "ILAMOSHE",
    "ILASAMAJA",
    "ISHAGA/IRE-AKARI",
    "MAFOLUKU",
    "OGUNNOLOKO",
    "OKE-AFA",
    "OKOTA",
    "OLUYEYE",
    "SHOGUNLE",
  ],
  "Shomolu": [
    "AIYETORO/MAFOWOKU",
    "AKOKA/ANU-OLUWAPO",
    "APELEHIN",
    "BAJULAIYE",
    "BASHUA EAST &WEST",
    "IBUOWO/OWOTUTU",
    "IGBARI",
    "IGBOBI/FADEYI",
    "IJEBU TEDO",
    "ILAJE",
    "OKESUNA/ALASE",
    "ONIPANU",
    "ORILE SOMOLU/ALADE",
    "OWODE /ORILE BARIGA",
    "PEDRO/GBAGADA",
    "SERIKI-OKUTA",
  ],
  "Surulere": [
    "ADENIRAN OGUNSANYA",
    "AGUNBIADE",
    "AIRWAYS",
    "AKINHANMI COLE",
    "ARALILE",
    "BABATUNDE AYILARA",
    "BALE",
    "BARUWA",
    "COKER",
    "GBAJA OBELE-ODAN",
    "IPONRI/ ERIC MOORE",
    "IRONE",
    "JINADU AIYETORO",
    "MOSAFEJO OJUELEGBA",
    "NURU ONIWO",
    "OBELE ONIWALA",
    "ODO-OLOWU",
    "OGUNSAMI/KAROUNWI",
    "OSHO",
    "RAMONI",
    "SANUSI I",
    "SAVAGE",
    "SHITTA BANK OLEMOH",
  ],
};
