project_id = "wwhkfahlmivbqbtyidfr"

[functions.send-ai-reminder]
verify_jwt = false

[functions.setup-account]
verify_jwt = false

[functions.invite-user]
verify_jwt = false

[functions.revoke-invitation]
verify_jwt = false

[functions.search-client]
verify_jwt = false

[functions.notify-transfer]
verify_jwt = false

[functions.chat-assistant]
verify_jwt = false

[functions.whatsapp-status-webhook]
verify_jwt = false

[functions.update-member]
verify_jwt = false

