// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxarmttwdqepbdaemqjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4YXJtdHR3ZHFlcGJkYWVtcWpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTI3NTcsImV4cCI6MjA2NTU2ODc1N30.EPlyODSLANP8rMx2BtG7cHSOhJHF-7ciXCY5ZgQ5ITo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);